### ISSUE TITLE
Thoughts on using rustc-serialize and serde

### ISSUE THREAD

**Issue by RandomInsano** [jaysonsantos/bmemcached-rs#5]
Instead of declaring a custom trait for serializing, have you thought about using the two leading serializers for this? I'd be willing to take a stab at implementing that using optional features.

I think using [conditional compilation](https://doc.rust-lang.org/book/conditional-compilation.html) depending on the feature needed. Thoughts?

**Comment by jaysonsantos** [comment]
Hi, I created the treats so users can use their serializing system for other complex objects and I did provide  the basic ones that I could easily encode. I didn't use any serializer because I want to leave that decision to the users as they know their structures.
But if you think that it can be improved with the use of a serializer + conditional compiling, go for it, I would happily accept new patches.
I started this project just to learn rust and in the and I kinda like it and tried to make it better but these days I am kinda out of time.
Thanks!

**Comment by RandomInsano** [comment]
After spending some time thinking about this, I agree with you. I think it's probably best not to serialize individual objects. The main reason being if you wanted to plug in features within the data pipeline (say, compress all data going outbound) then serializing for users isn't very helpful.
